import { useMemo } from "react";
import { useNavigate, useParams } from "react-router-dom";
import Button from "../components/ui/Button.jsx";
import Sky from "../components/ui/Sky.jsx";
import { getLevelById } from "../data/levels.js";
import { getChapterIdForNode } from "../lib/checkpointProgression.js";
import { buildNodeExercises } from "../lib/nodeExercises.js";
import { completeNode } from "../lib/nodeProgression.js";
import { useProgress } from "../lib/ProgressContext.jsx";
import Lesson from "./Lesson.jsx";

/* dujeen-quest-gameplay-prompts.md Prompt 4 follow-up - swaps the legacy
   GamePage/QuestionRenderer engine (still used by /classic) for the real
   Lesson.jsx exercise engine, using vocab.json-backed exercises generated by
   lib/nodeExercises.js instead of levels.js's old question types (pinyin
   drag, tone choice, etc.), which no longer render here.

   completeNode still reads `level.questions.length` for star math, not the
   generated exercise count, so scoring stays sane even though the two counts
   differ now. What it can't do anymore: match wrong answers back to a
   specific levels.js question id, since the generated exercises use their
   own ids - mistakes-review and checkpoint "weakest lesson" tracking for
   nodes played through this route are stale until that's rebuilt against
   the new id shape. Deliberately deferred, not an oversight. */
export default function RouteLesson() {
  const { lessonId } = useParams();
  const navigate = useNavigate();
  const { progress, setProgress } = useProgress();
  const nodeId = Number(lessonId);
  const level = getLevelById(nodeId);
  const chapterId = getChapterIdForNode(nodeId);
  const mapPath = chapterId ? `/chapter/${chapterId}` : "/chapters";
  const exercises = useMemo(() => buildNodeExercises(nodeId), [nodeId]);

  if (!level || !exercises.length) {
    return (
      <div className="lantern-app">
        <Sky />
        <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", gap: "16px", padding: "20px" }}>
          <p>ไม่พบโหนดนี้</p>
          <Button onClick={() => navigate(mapPath)}>กลับแผนที่</Button>
        </main>
      </div>
    );
  }

  const handleComplete = (summary) => {
    const outcome = completeNode(progress, level, {
      correct: summary.correctCount,
      score: summary.correctCount * 10,
      attemptedCount: summary.total,
    });
    setProgress(outcome.progress);
    navigate(`/result/${level.id}`, { state: { outcome, comboMax: summary.comboMax, elapsedMs: summary.elapsedMs } });
  };

  return <Lesson exercises={exercises} onExit={() => navigate(mapPath)} onComplete={handleComplete} />;
}
